version: '3.8'

services:
  webhook-server:
    build: .
    container_name: mdtalkman-webhook
    ports:
      - "8080:8080"
    environment:
      # Server configuration
      - PORT=8080
      
      # GitHub webhook secret (set this in your .env file)
      - GITHUB_WEBHOOK_SECRET=${GITHUB_WEBHOOK_SECRET}
      
      # iOS app configuration
      - BUNDLE_ID=${BUNDLE_ID:-ganglinwu.MD-TalkMan}
      
      # APNs configuration
      - APNS_DEVELOPMENT=${APNS_DEVELOPMENT:-true}
      - APNS_KEY_PATH=${APNS_KEY_PATH:-/app/certs/AuthKey.p8}
      - APNS_KEY_ID=${APNS_KEY_ID}
      - APNS_TEAM_ID=${APNS_TEAM_ID}
      - APNS_CERT_PATH=${APNS_CERT_PATH}
      
    volumes:
      # Mount certificates/keys directory
      - ./certs:/app/certs:ro
      
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M

# Optional: Add nginx reverse proxy for SSL termination
  nginx:
    image: nginx:alpine
    container_name: mdtalkman-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - webhook-server
    restart: unless-stopped
    profiles: ["with-nginx"]  # Only start with --profile with-nginx